### ISSUE TITLE
could not start qseis: "qseis"

### ISSUE THREAD

**Issue by irmakts** [pyrocko/pyrocko#167]
Dear All,

I am trying to calculate green functions (fomosto build --force) but I got error messages given below.
Any help will appreciate. 

T. Serkan Irmak

fomosto:fomosto.qseis        - INFO     - Starting block 1 / 2
fomosto:fomosto.qseis        - INFO     - Starting block 2 / 2
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/parimap.py", line 15, in worker
    r = function(*args)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/builder.py", line 66, in __work_block
    builder.work_block(iblock)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/qseis.py", line 749, in work_block
    runner.run(conf)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/qseis.py", line 576, in run
    raise QSeisError('could not start qseis: "%s"' % program)
QSeisError: could not start qseis: "qseis"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/parimap.py", line 15, in worker
    r = function(*args)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/builder.py", line 66, in __work_block
    builder.work_block(iblock)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/qseis.py", line 749, in work_block
    runner.run(conf)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/qseis.py", line 576, in run
    raise QSeisError('could not start qseis: "%s"' % program)
QSeisError: could not start qseis: "qseis"
fomosto: error: could not start qseis: "qseis"

**Comment by hvasbath** [comment]
Looks like you did not install qseis?

Please check this link:
https://github.com/pyrocko/fomosto-qseis

**Comment by emolch** [comment]
Please also check if you are using the latest Pyrocko version, current version would try to call `fomosto_qseis2006a` rather than `qseis`.

**Comment by irmakts** [comment]
thanks for quick responses. It supposed to be installed but seems not installed. I am going to try install it.
