### ISSUE TITLE
Installation problem on Ubuntu 14.04 x86

### ISSUE THREAD

**Issue by mohseniaref** [pyrocko/pyrocko#227]
Dear all,
I have installed all pre and pyrocko using sudo python setup.py install without any problem but when I have tried to do test using ./test.sh
I faced this error as you in the end of message.
Would you please guid eme how to solve this problem?

Best Regards,
Mohammad
earth@naranj:~/Software/pyrocko/pyrocko$ ./test.sh
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/earth/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
.sss.................ss........EEtest_all:test_gf_qseis        - WARNING  - qseis not installed; skipping test_pyrocko_gf_vs_qseis
.test_all:test_gf_qseis        - WARNING  - qseis not installed; skipping test_pyrocko_gf_vs_qseis
............EE.......s......ss.....test_all:test_gf.py           - WARNING  - test_stf_pre_post: max difference of 2.0 %
test_all:test_gf.py           - WARNING  - test_stf_pre_post: max difference of 2.0 %
.......test...
41230 745
..............sssssssss..E.................................................................................................................................................................ss...............test_all:test_fomosto_report  - WARNING  - qseis not installed; skipping test_pyrocko_gf_vs_qseis
............................................|   3.33E-12 |
|   3.33E-11 |
|   3.33E-10 |
|   3.33E-09 |
|   3.33E-08 |
|   3.33E-07 |
|   3.33E-06 |
|   3.33E-05 |
|   3.33E-04 |
|   3.33E-03 |
|   3.33E-02 |
|   0.333    |
|   3.33     |
|  33.3      |
| 333.       |
|   3.33E+03 |
|   3.33E+04 |
|   3.33E+05 |
|   3.33E+06 |
|   3.33E+07 |
|   3.33E+08 |
|   3.33E+09 |
|   3.33E+10 |
....
======================================================================
ERROR: test_url_alive (test_fdsn.FDSNStationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/earth/Software/pyrocko/pyrocko/test/test_fdsn.py", line 178, in test_url_alive
    fdsn_ws._request(url[0])
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fdsn/ws.py", line 109, in _request
    resp = urllib2.urlopen(req, timeout=g_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer

======================================================================
ERROR: test_fomosto_vs_psgrn_pscmp (test_gf_psgrn_pscmp.GFPsgrnPscmpTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/earth/Software/pyrocko/pyrocko/test/test_gf_psgrn_pscmp.py", line 120, in test_fomosto_vs_psgrn_pscmp
    psgrn_pscmp.build(store_dir, nworkers=1)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/psgrn_pscmp.py", line 1496, in build
    step=step, iblock=iblock)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/builder.py", line 147, in build
    Interrupted, store.StoreError)):
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/parimap.py", line 46, in parimap
    yield function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/builder.py", line 66, in __work_block
    builder.work_block(iblock)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/psgrn_pscmp.py", line 1347, in work_block
    runner.run(cg, force=self.force)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/psgrn_pscmp.py", line 358, in run
    ''' % program)
PsGrnError: could not start psgrn executable: "fomosto_psgrn2008a"
Available fomosto backends and download links to the modelling codes are listed
on

      http://pyrocko.org/current/apps/fomosto/backends.html

======================================================================
ERROR: test_process_static (test_gf_static.GFStaticTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/earth/Software/pyrocko/pyrocko/test/test_gf_static.py", line 213, in test_process_static
    engine = gf.LocalEngine(store_dirs=[self.get_pscmp_store_dir()])
  File "/home/earth/Software/pyrocko/pyrocko/test/test_gf_static.py", line 44, in get_pscmp_store_dir
    self.pscmp_store_dir = self._create_psgrn_pscmp_store()
  File "/home/earth/Software/pyrocko/pyrocko/test/test_gf_static.py", line 108, in _create_psgrn_pscmp_store
    psgrn_pscmp.build(store_dir, nworkers=1)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/psgrn_pscmp.py", line 1496, in build
    step=step, iblock=iblock)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/builder.py", line 147, in build
    Interrupted, store.StoreError)):
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/parimap.py", line 46, in parimap
    yield function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/builder.py", line 66, in __work_block
    builder.work_block(iblock)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/psgrn_pscmp.py", line 1347, in work_block
    runner.run(cg, force=self.force)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/psgrn_pscmp.py", line 358, in run
    ''' % program)
PsGrnError: could not start psgrn executable: "fomosto_psgrn2008a"
Available fomosto backends and download links to the modelling codes are listed
on

      http://pyrocko.org/current/apps/fomosto/backends.html

======================================================================
ERROR: test_sum_static (test_gf_static.GFStaticTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/earth/Software/pyrocko/pyrocko/test/test_gf_static.py", line 270, in test_sum_static
    store = gf.Store(self.get_qseis_store_dir())
  File "/home/earth/Software/pyrocko/pyrocko/test/test_gf_static.py", line 38, in get_qseis_store_dir
    self.qseis_store_dir = self._create_qseis_store()
  File "/home/earth/Software/pyrocko/pyrocko/test/test_gf_static.py", line 177, in _create_qseis_store
    qseis.build(store_dir, nworkers=1)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/qseis.py", line 1034, in build
    step=step, iblock=iblock)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/builder.py", line 147, in build
    Interrupted, store.StoreError)):
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/parimap.py", line 46, in parimap
    yield function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/builder.py", line 66, in __work_block
    builder.work_block(iblock)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/qseis.py", line 860, in work_block
    runner.run(conf)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/fomosto/qseis.py", line 622, in run
    ''' % program)
QSeisError: could not start qseis executable: "fomosto_qseis2006a"
Available fomosto backends and download links to the modelling codes are listed
on

      http://pyrocko.org/current/apps/fomosto/backends.html

======================================================================
ERROR: testArray (test_guts.GutsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/earth/Software/pyrocko/pyrocko/test/test_guts.py", line 526, in testArray
    b = load_xml_string(a.dump_xml())
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 1542, in load_xml_string
    return load_xml(string=s, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 116, in g
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 1538, in load_xml
    return _load_xml(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 1368, in _load_xml
    return g.next()
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 1354, in _iload_all_xml
    parser.Parse(data, bool(not data))
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 1301, in end_element
    o.validate(regularize=True, depth=1)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 645, in validate
    self.T.instance.validate(self, regularize, depth)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 375, in validate
    val = validator.validate_children(val, regularize, depth)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 387, in validate_children
    newpropval = prop.validate(propval, regularize, depth-1)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 372, in validate
    validator.validate_extra(val)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts_array.py", line 139, in validate_extra
    if self.dtype is not None and self.dtype != val.dtype:
AttributeError: 'unicode' object has no attribute 'dtype'

----------------------------------------------------------------------
Ran 328 tests in 150.732s

FAILED (errors=5, skipped=19)
earth@naranj:~/Software/pyrocko/pyrocko$

**Comment by emolch** [comment]
@miili can you reproduce the guts bug?
