### ISSUE TITLE
Unable to run 'fomosto report' command

### ISSUE THREAD

**Issue by Johumel** [pyrocko/pyrocko#229]
Hi Fomosto Team,
Thanks for putting this package together. I am trying to run the fomosto report command and ran into this error. I am not sure if it is a problem from my end or a bug in the code.

```
$ fomosto report single ./report_config --output=~/GF
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py:800: MatplotlibDeprecationWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  mplDeprecation)
Traceback (most recent call last):
  File "/usr/local/bin/fomosto", line 1136, in <module>
    globals()['command_' + command](args)
  File "/usr/local/bin/fomosto", line 1122, in command_report
    report_call.run_program(args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyrocko/fomosto_report/report_call.py", line 496, in run_program
    lst = globals()['command_' + command](command, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyrocko/fomosto_report/report_call.py", line 240, in command_single
    gft = gftest.createDocumentFromFile(filename, **opts)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyrocko/fomosto_report/report_main.py", line 1439, in createDocumentFromFile
    gft.createOutputDoc()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyrocko/fomosto_report/report_main.py", line 683, in createOutputDoc
    artefacts]], chapters)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyrocko/fomosto_report/report_main.py", line 597, in __createOutputDoc
    subprocess.call(pro_call)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by emolch** [comment]
Looks like it is not finding pdflatex. Is it installed?

**Comment by emolch** [comment]
You can also run it with `--output-format=html` then it shouldn't need pdflatex

**Comment by emolch** [comment]
I will change the code to emit a more meaningful error message.

**Comment by emolch** [comment]
better error message in c6f4b10be8965ed6f48b549f726c2e3893f4c25b

**Comment by Johumel** [comment]
Thanks. It's working now.
