### ISSUE TITLE
Error when using ConfigTypeC Class for fomosto ttt

### ISSUE THREAD

**Issue by blubbblub** [pyrocko/pyrocko#232]
Config file for Fomosto:

--- !pf.ConfigTypeC
id: aspo2
modelling_code_id: ahfullgreen
earthmodel_1d: |2
      0.             5.8             3.2             2.72           2000.           1000.
     30.             5.8             3.2             2.72           2000.           1000.
sample_rate: 100000.0
component_scheme: elastic10
tabulated_phases:
- !pf.TPDef
  id: anyP
  definition: P,p,\P,\p
- !pf.TPDef
    id: anyS
    definition: S,s,\S,\s
ncomponents: 10
receivers:
- !pf.Receiver
  north_shift: 7304.13
  east_shift: 2413.71
  depth: 406.49
  codes: [ASPO, AE01, TASN]
source_origin:
- !pf.Location
  north_shift: 7320.0
  east_shift: 2410.0
  depth: 410.0 
source_depth_min: 380.0
source_depth_max: 420.0
source_depth_delta: 0.1
source_east_shift_min: 2390.0
source_east_shift_max: 2420.0
source_east_shift_delta: 0.1
source_north_shift_min: 7295.0
source_north_shift_max: 7320.0
source_north_shift_delta: 0.1

Error:

fomosto ttt
Traceback (most recent call last):
  File "/usr/local/bin/fomosto", line 1136, in <module>
    globals()['command_' + command](args)
  File "/usr/local/bin/fomosto", line 765, in command_ttt
    store = gf.Store(store_dir)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/store.py", line 1131, in __init__
    self.config = meta.load(filename=config_fn)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 99, in g
    retval = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 1518, in load
    return _load(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 1231, in _load
    return yaml.load(stream=stream, Loader=SafeLoader)
  File "/home/******/.local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/******/.local/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/home/******/.local/lib/python2.7/site-packages/yaml/constructor.py", line 43, in construct_document
    data = self.construct_object(node)
  File "/home/******/.local/lib/python2.7/site-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 1263, in multi_constructor
    o = cls(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/meta.py", line 1628, in __init__
    self.validate(regularize=True, depth=1)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 651, in validate
    self.T.instance.validate(self, regularize, depth)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 378, in validate
    val = validator.validate_children(val, regularize, depth)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 390, in validate_children
    newpropval = prop.validate(propval, regularize, depth-1)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 355, in validate
    val = self.regularize_extra(val)
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/guts.py", line 383, in regularize_extra
    return self.cls(val)
TypeError: __init__() takes exactly 1 argument (2 given)

**Comment by hvasbath** [comment]
The config you posted has type B ..., your heading says C ...? Which one now?

**Comment by blubbblub** [comment]
It's TypeC. I pasted the wrong file... updated now.

**Comment by hvasbath** [comment]
Your specifications contradict each other. C is for 3d medium right? ahfull is analytic HOMOENEOUS fullspace. So no 3d GFs here and also you would need to specify component scheme elastic18 to take advantage of 3d GFs.

**Comment by hvasbath** [comment]
For later users that might stumble upon it. Solved through personal comunication:
intended were 3d reciever positions rather than 3d GFs. SO COnfigTypeB sufficient and works then.
