### ISSUE TITLE
converting cube data using jackseis aborts with "antidrift" error

### ISSUE THREAD

**Issue by EvaMuc** [pyrocko/pyrocko#288]
I tried to convert cube data to mseed data using jackseis and python 3. 3 out of 4 stations work perfectly. The fourth one gives me an error. The command I use is: 
"jackseis A7X/ --tinc=86400  --rename-network=/^/VI/  --rename-station=/A7X/G4/  --rename-channel=/p0/HHZ/  --rename-channel=/p1/HHN/  --rename-channel=/p2/HHE/  --output='2017-18_mseed/%s/%c/VI.%s..%c.2018.%j.mseed'"
and the error I get is:
Scanning files done
jackseis:pyrocko.pile         - WARNING  - Unknown file format: /media/eibl/Seagate Expansion Drive/_backup/Geyser_2017-18/A7X/CONFIG.TXT
jackseis:pyrocko.pile         - WARNING  - Unknown file format: /media/eibl/Seagate Expansion Drive/_backup/Geyser_2017-18/A7X/STATION.TXT
jackseis:pyrocko.pile         - WARNING  - The following files caused problems and will be ignored:
/media/eibl/Seagate Expansion Drive/_backup/Geyser_2017-18/A7X/CONFIG.TXT
/media/eibl/Seagate Expansion Drive/_backup/Geyser_2017-18/A7X/STATION.TXT
jackseis:pyrocko.apps.jackseis - INFO     - processing 2017-12-15 00:00:00.000 - 2017-12-16 00:00:00.000, 3 traces
jackseis:pyrocko.apps.jackseis - INFO     - processing 2017-12-16 00:00:00.000 - 2017-12-17 00:00:00.000, 3 traces
jackseis:pyrocko.apps.jackseis - INFO     - processing 2017-12-17 00:00:00.000 - 2017-12-18 00:00:00.000, 3 traces
Traceback (most recent call last):
  File "/usr/local/bin/jackseis", line 9, in <module>
    load_entry_point('pyrocko==2018.1.29', 'console_scripts', 'jackseis')()
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/apps/jackseis.py", line 388, in main
    for traces in it:
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/pile.py", line 1299, in chopper_grouped
    for traces in self.chopper(*args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/pile.py", line 1220, in chopper
    include_last, load_data)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/pile.py", line 1080, in chop
    if tr.file.load_data():
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/pile.py", line 784, in load_data
    substitutions=self.substitutions)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/io/__init__.py", line 66, in load
    filename, format=format, getdata=getdata, substitutions=substitutions))
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/io/__init__.py", line 162, in iload
    filename, load_data=load_data, **add_args.get(format, {})):
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/io/datacube.py", line 418, in iload
    arr.astype(num.float), tmin_ip, deltat, ydata)
pyrocko.signal_ext.Error: antidrift failed.

**Comment by emolch** [comment]
Hi thanks for reporting! I would need the data snippet causing the trouble to hunt the bug. Could you please make it available somehow?

**Comment by EvaMuc** [comment]
Hi,
thanks for looking into this. Here is a link to the data: https://www.dropbox.com/sh/gfv7e5r5msd1rdk/AAAK1GUoL5X-s6WwvdiD2hFna?dl=0
The conversion of .A7X gives an "anitdrift failed" error. .A7Z should work without problems. 
Thanks,
Eva
