### ISSUE TITLE
issue with distazi.dat.tmp

### ISSUE THREAD

**Issue by RedouaneNouh** [pyrocko/pyrocko#299]
Good morning,
I'm totally new with the kiwi tools and programming, and I just started with rapidin code to use kiwi tools
whenever I run "./rapidin rapidinv.input" I got this error:
**Initializing
Read input file, check and prepare inversion parameters
Prepare inversion directory, choose stations, prepare data
Taper applied
copied data from /home/redouane/kiwitest/playground/data/oklahoma_20160903_120246/prepared
radius 0 set to  4000.0
Calling minimizer /home/redouane/kiwitest/playground/inverttest/minimizer.inp.dist
1 /home/redouane/kiwitest/playground/inverttest/minimizer.inp.dist /home/redouane/kiwitest/playground/inverttest/minimizer.out.dist
2 minimizer < /home/redouane/kiwitest/playground/inverttest/minimizer.inp.dist > /home/redouane/kiwitest/playground/inverttest/minimizer.out.dist
Fortran runtime error: Zero length string(s) passed to getenv.
Traceback (most recent call last):
  File "./rapidinv", line 6736, in <module>
    prepStations(inv_param,traces)
  File "./rapidinv", line 789, in prepStations
    f = open(fdistazitmp,'r')
IOError: [Errno 2] No such file or directory: '/home/redouane/kiwitest/playground/inverttest/distazi.dat.tmp'**

I thing kiwi is well installed, the "gfdb_info" gives:
**usage: gfdb_info database

documentation:  http://kinherd.org/power/trac/wiki/GFDBInfoTool
STOP 1**

Can you please tell me what I'm doing wrong? or how to fix this; 
Thank you

**Comment by emolch** [comment]
Hello,
could by, that the `KIWI_HOME` environment variable isn't set.
Put this into your `~/.bashrc`:
```
export KIWI_HOME=/usr/local/share/kiwi
```

best wishes
Sebastian

**Comment by RedouaneNouh** [comment]
Thank you for your response, I did set the environment variable, but I still get the same error

**Comment by emolch** [comment]
Can you confirm that `echo $KIWI_HOME` shows the correct directory? Just in case - you did open a new terminal after setting it in `~/.bashrc`?

**Comment by RedouaneNouh** [comment]
oh, you were right, i had to open an other terminal; it shows the correct directory. Thank you.
but another error came up it's:
ERROR 1: n start sol <> n point sol (minimizer.out)

do you have any idea?
