### ISSUE TITLE
problem when trying example in manual

### ISSUE THREAD

**Issue by CovMat** [pyrocko/pyrocko#301]
Dear developer:

when I try the example in manual:
```
cake plot-rays --classic=Pdiff,PKP,PKIKP --distances=110:150:5 --degrees
```

I got a error:
```
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/cake", line 11, in <module>
    load_entry_point('pyrocko==2018.1.29', 'console_scripts', 'cake')()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyrocko/apps/cake.py", line 712, in main
    phase_colors=c.phase_colors)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyrocko/plot/cake_plot.py", line 618, in my_rays_plot_gcs
    axes = plt.subplot(1, 1, 1, projection='globe_cross_section')
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1072, in subplot
    a = fig.add_subplot(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1239, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_subplots.py", line 77, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/projections/polar.py", line 854, in __init__
    Axes.__init__(self, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 502, in __init__
    self.set_figure(fig)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 645, in set_figure
    self._set_lim_and_transforms()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pyrocko/plot/cake_plot.py", line 78, in _set_lim_and_transforms
    self._theta_label1_position +
AttributeError: 'GlobeCrossSectionAxesSubplot' object has no attribute '_theta_label1_position'
```

But if I remove the ```--degrees```, and try ```cake plot-rays --classic=Pdiff,PKP,PKIKP --distances=110:150:5 ```, it works well.

I do not know where the problem is. Could you please help me? Thank you very much!

**Comment by emolch** [comment]
This bug should already be fixed in the current master branch of Pyrocko, since commit 281a9f8d93e42d93b8ed23ec965246483147c1a4. Anaconda package will be updated soon.

**Comment by emolch** [comment]
Anaconda packages are updated. Please check if the problem persists.
