### ISSUE TITLE
Geofon response request timed out

### ISSUE THREAD

**Issue by braunfuss** [pyrocko/pyrocko#306]
When requesting level='response' with fdsn.station for site='geofon' and selections of BHZ stations for distances over 20° return the following error, which is not the case for site='iris' :
Traceback (most recent call last):
  File "/media/asteinbe/decepticon/backprojections/Waveform/pyrocko_down.py", line 199, in <module>
    site=site, selection=selection_geofon, level='response')
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/client/fdsn.py", line 264, in station
    return stationxml.load_xml(stream=_request(url, **params))
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/client/fdsn.py", line 135, in _request
    resp = urlopen_(req, **url_args)
  File "/usr/lib/python3.5/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python3.5/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python3.5/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python3.5/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.5/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python3.5/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python3.5/ssl.py", line 643, in read
    v = self._sslobj.read(len)
ssl.SSLError: ('The read operation timed out',)

It also works fine with smaller distance selections.

**Comment by gesape** [comment]
Hi Andi,
did you try just setting the g_timeout a bit higher? maybe there is just too much data coming for the default?
it is in src/client/fdsn.py the g_timeout. helped for me when i downloaded a lot of data at once.
but anyway, in my experience sometimes geofon fdsn download does not work properly one day but next day it is fine again...

**Comment by braunfuss** [comment]
Hey Gesa, yes i set it higher but that didn't help (also strange that g_timeout is hardcoded)- i also noticed that the amount of data to be requested varies from day to day. I solved it for me by using a subdivision of the distances selection to download and stitching it up together afterwards. Thats was fairly fast. We could also implement this for the geofon request in general then in an try loop, if it is not only my problem.

**Comment by emolch** [comment]
1) Let's make the timeout be configurable in in the `.pyrocko/config.pf`, as an entry `fdsn_timeout`, also we should add a kwarg `timeout` to the request functions. Both should have default value of `None`. If both are set to `None` the old `g_timeout` should be used. Precedence should be (kwarg, configfile, global). It is necessary to support the old behavior because there are several scripts out in the wild which do, e.g.
``` Python
from pyrocko.client import fdsn
fdsn.g_timeout = 60.
```

2) Chunking of requests is important, rather than doing distance chunks, consider splitting the list of `(net, sta, loc, cha, tmin, tmax)` given to the `selection=...` kwarg into chunks of equal length. E.g. 50 per request. See for example in this script: https://github.com/pyrocko/grond/blob/master/examples/grond-playground-regional/bin/grondown

**Comment by emolch** [comment]
I would rather not implement automatic chunking of the requests in the rather low-level `pyrocko.client.fdsn`. Chunking should be functionality of a highlevel downloader.

**Comment by braunfuss** [comment]
Sounds fine to me, we should also make a rudimentary partial download script example available in the general examples.

**Comment by emolch** [comment]
Let's keep it open until the work is done...

**Comment by braunfuss** [comment]
See Pull request for g_timeout in config.
Another problem:
Even when chunking the request issues with server connection arise incoherently. This error pops up for geofon request sometimes:
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
However, sometimes it also does not. So without changing anything from our side, the gefon sever seems not to respond correctly from time to time.
