### ISSUE TITLE
seismosizer snuffling

### ISSUE THREAD

**Issue by hvasbath** [pyrocko/pyrocko#316]
Loaded traces, stations and event in snuffler, clicked on seismosizer(builtin) snuffling:

pyrocko.gui.snuffling - ERROR    Seismosizer (builtin): Snuffling action raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gui/snuffling.py", line 1550, in check_call
    self.call()
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/gui/snufflings/seismosizer.py", line 179, in call
    source.regularize()
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/guts.py", line 778, in regularize
    self.validate(regularize=True, depth=depth)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/guts.py", line 775, in validate
    self.T.instance.validate(self, regularize, depth)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/guts.py", line 468, in validate
    val = self.regularize_extra(val)
  File "/usr/local/lib/python3.5/dist-packages/pyrocko/guts.py", line 493, in regularize_extra
    return self.cls(val)
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by HerrMuellerluedenscheid** [comment]
Hey @hvasbath ,
I just tested the current hyposat snuffling and it seems to work fine. Can you provide the data that caused the crash?

**Comment by hvasbath** [comment]
Sorry I totally forgot, which data I was working with back then. Lets close the issue for now. I will reopen in case I will try again and it happens...
