### ISSUE TITLE
Error for "unpack_fixed" when reading a hyposat velocity file

### ISSUE THREAD

**Issue by john-robert** [pyrocko/pyrocko#319]
When trying to read a velocity model via:

`cake plot-model --model model.txt --format 'hyposat'`

I get this error thrown:
```
Traceback (most recent call last):

  File "/Users/mmustermann/anaconda3/envs/py2/bin/cake", line 11, in <module>
    sys.exit(main())
  File "/Users/mmustermann/anaconda3/envs/py2/lib/python2.7/site-packages/pyrocko/apps/cake.py", line 725, in main
    c = optparse(('model',), (), usage=subusage, descr=descr)
  File "/Users/mmustermann/anaconda3/envs/py2/lib/python2.7/site-packages/pyrocko/apps/cake.py", line 327, in optparse
    options.model_filename, options.model_format)
  File "/Users/mmustermann/anaconda3/envs/py2/lib/python2.7/site-packages/pyrocko/cake.py", line 3893, in load_model
    mod = LayeredModel.from_scanlines(reader)
  File "/Users/mmustermann/anaconda3/envs/py2/lib/python2.7/site-packages/pyrocko/cake.py", line 3382, in from_scanlines
    for z, material, name in producer:
  File "/Users/mmustermann/anaconda3/envs/py2/lib/python2.7/site-packages/pyrocko/cake.py", line 3717, in read_hyposat_model
    z, vp, vs, name = util.unpack_fixed('f10, f10, f10, a4', line)
  File "/Users/mmustermann/anaconda3/envs/py2/lib/python2.7/site-packages/pyrocko/util.py", line 1267, in unpack_fixed
    ln = int(form[1:])
ValueError: invalid literal for int() with base 10: 'f10'
```

I believe my file is as it should be. Could it be that I am doing something wrong?
[model.txt](https://github.com/pyrocko/pyrocko/files/2529302/model.txt)

**Comment by john-robert** [comment]
[model.txt](https://github.com/pyrocko/pyrocko/files/2529313/model.txt)

**Comment by john-robert** [comment]
sorry, by accident closed this issue

**Comment by miili** [comment]
Thanks for the bug report. Fixed in https://github.com/pyrocko/pyrocko/commit/85eda1cd3eb9284e3753f786a68c073331934131
