### ISSUE TITLE
Fomosto doesn't build for certain distance and depth ranges

### ISSUE THREAD

**Issue by axelwang** [pyrocko/pyrocko#328]
Hey,
  I have the following `config` file: 

  `--- !pf.ConfigTypeA
id: test
modelling_code_id: qssp
regions: []
references: []
earthmodel_1d: |2` 

Earth model is omitted. 

`sample_rate: 0.2
component_scheme: elastic10
tabulated_phases:
- !pf.TPDef
  id: begin
  definition: p,P,p\,P\,Pv_(cmb)p
- !pf.TPDef
  id: end
  definition: '2.5'
- !pf.TPDef
  id: P
  definition: '!P'
- !pf.TPDef
  id: S
  definition: '!S'
- !pf.TPDef
  id: p
  definition: '!p'
- !pf.TPDef
  id: s
  definition: '!s'
ncomponents: 
receiver_depth: 0.0
source_depth_min: 0.0
source_depth_max: 100000.0
source_depth_delta: 4000.0
distance_min: 20000.0
distance_max: 20000000.0
distance_delta: 20000.0`

Note that this is simply a combination of the default `config` file created by `fomosto init qssp.2010` except the source depth and distance ranges are changed to those from the `config` file of a published GF store, 'global_2s', i.e. a working one. Then, when I try to build with the `config` file shown above, I got the following error: 
`Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/meta.py", line 482, in evaluate
    times = [phase(args) for phase in phases]
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/meta.py", line 482, in <listcomp>
    times = [phase(args) for phase in phases]
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/spit.py", line 347, in __call__
    return self.interpolate(x)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/spit.py", line 342, in interpolate
    raise OutOfBounds()
pyrocko.spit.OutOfBounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/fomosto", line 11, in <module>
    load_entry_point('pyrocko==2018.1.29', 'console_scripts', 'fomosto')()
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/apps/fomosto.py", line 1175, in main
    globals()['command_' + command](args)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/apps/fomosto.py", line 315, in command_build
    iblock=iblock)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/fomosto/qssp.py", line 889, in build
    step=step, iblock=iblock)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/builder.py", line 116, in build
    builder = cls(store_dir, step, shared, force=force)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/fomosto/qssp.py", line 608, in __init__
    conf.time_region[0], conf.time_region[1])
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 1630, in make_timing_params
    tmin = self.t(begin, args)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 1608, in t
    return timing.evaluate(self.get_phase, args)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/meta.py", line 496, in evaluate
    raise OutOfBounds(args)
pyrocko.gf.meta.OutOfBounds: out of bounds: (0,20000)
Exception ignored in: <bound method BaseStore.__del__ of <pyrocko.gf.store.Store object at 0x1c1f21b908>>
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 365, in __del__
    self.close()
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 419, in close
    self.open()
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 1157, in open
    BaseStore.open(self)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 361, in open
    self._load_index()
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 918, in _load_index
    mode=('r', 'r+')[self.mode == 'w'])
  File "/anaconda3/lib/python3.6/site-packages/numpy/core/memmap.py", line 205, in __new__
    import mmap
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
TypeError: 'NoneType' object is not iterable
`
I think the main errors are: 
`pyrocko.gf.meta.OutOfBounds: out of bounds: (0,20000)` and 
`TypeError: 'NoneType' object is not iterable`, but I do not know hot to fix them. 

  Thank you so much for so much help! 

  Axel

**Comment by emolch** [comment]
The error comes from a lookup in the travel-time-table which is out of bounds. Could be a result of running `fomosto build` without a prior `fomosto ttt`.

**Comment by axelwang** [comment]
Hey,
  By running `fomosto ttt`, the first error does go away! 

  However, the second error still persists for the following situation:

  If I take the range parameters of, say, Global_2s, which are:
  `source_depth_min: 0.0
source_depth_max: 100000.0
source_depth_delta: 4000.0
distance_min: 20000.0
distance_max: 20000000.0
distance_delta: 20000.0`

  and now changes the end phase from `'2.5'`, to `S`, i.e. 
`- !pf.TPDef
  id: end
  definition: S`
  
  Then, `TypeError: 'NoneType' object is not iterable` error still occurs. 

  The whole error message is:
  `Traceback (most recent call last):
  File "/anaconda3/bin/fomosto", line 11, in <module>
    load_entry_point('pyrocko==2018.1.29', 'console_scripts', 'fomosto')()
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/apps/fomosto.py", line 1175, in main
    globals()['command_' + command](args)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/apps/fomosto.py", line 315, in command_build
    iblock=iblock)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/fomosto/qssp.py", line 889, in build
    step=step, iblock=iblock)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/builder.py", line 116, in build
    builder = cls(store_dir, step, shared, force=force)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/fomosto/qssp.py", line 608, in __init__
    conf.time_region[0], conf.time_region[1])
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 1664, in make_timing_params
    tlenmax_vred = num.nanmax(tmax - (tmin_vred + sred*x))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Exception ignored in: <bound method BaseStore.__del__ of <pyrocko.gf.store.Store object at 0x1c1675cac8>>
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 365, in __del__
    self.close()
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 419, in close
    self.open()
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 1157, in open
    BaseStore.open(self)
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 361, in open
    self._load_index()
  File "/anaconda3/lib/python3.6/site-packages/pyrocko/gf/store.py", line 918, in _load_index
    mode=('r', 'r+')[self.mode == 'w'])
  File "/anaconda3/lib/python3.6/site-packages/numpy/core/memmap.py", line 205, in __new__
    import mmap
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
TypeError: 'NoneType' object is not iterable`. 

  If I use the default range parameters from a newly initialized store 

 `source_depth_min: 10000.0
source_depth_max: 20000.0
source_depth_delta: 10000.0
distance_min: 100000.0
distance_max: 1000000.0
distance_delta: 10000.0`

  and making the same change for the end phase to `S` as in above. The GF builds without any problems. 

  Thanks in advance for the help!
