### ISSUE TITLE
pyrocko.gf.meta.OutOfBounds: out of bounds:

### ISSUE THREAD

**Issue by sergintav1** [pyrocko/pyrocko#349]
Hi 
I use local model to produce the green function and the codes gives the following error:

beat check bodrum --what=traces
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
models       - INFO     ... Initialising Geometry Optimizer ...

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

heart        - INFO     Consistent number of datasets and targets in any_P_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_P_0: 22
seismic      - INFO     The waveform defined in "slowest 1" config is not included in the optimization!
seismic      - INFO     The waveform defined in "any_S 2" config is not included in the optimization!
Traceback (most recent call last):
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/lib/python3.6/site-packages/pyrocko/gf/meta.py", line 482, in evaluate
    times = [phase(args) for phase in phases]
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/lib/python3.6/site-packages/pyrocko/gf/meta.py", line 482, in <listcomp>
    times = [phase(args) for phase in phases]
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/lib/python3.6/site-packages/pyrocko/spit.py", line 354, in __call__
    return self.interpolate(x)
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/lib/python3.6/site-packages/pyrocko/spit.py", line 349, in interpolate
    raise OutOfBounds()
pyrocko.spit.OutOfBounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0rc1', 'console_scripts', 'beat')()
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/apps/beat.py", line 1600, in main
    globals()['command_' + command](args)
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/apps/beat.py", line 1382, in command_check
    outmode='stacked_traces')
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/heart.py", line 2196, in prepare_data
    target=target, wavename=self.name)
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/heart.py", line 1974, in get_phase_arrival_time
    atime = store.t(wavename, (source.depth, dist)) + source.time
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/lib/python3.6/site-packages/pyrocko/gf/store.py", line 1623, in t
    return timing.evaluate(self.get_phase, args)
  File "/Users/sergintav/anaconda3/envs/GFZ_py3.7/lib/python3.6/site-packages/pyrocko/gf/meta.py", line 496, in evaluate
    raise OutOfBounds(args)
pyrocko.gf.meta.OutOfBounds: out of bounds: (4300,163488)

Also, I attached my config file:

[config_geometry.yaml.txt](https://github.com/pyrocko/pyrocko/files/2881507/config_geometry.yaml.txt)

How can I solve this problem?

**Comment by braunfuss** [comment]
Hello @sergintav1, this is really a beat issue i moved it there:
https://github.com/hvasbath/beat/issues/35
